### ISSUE TITLE
Architecture decision

### ISSUE THREAD

**Issue by Prashant-mahajan** [alvinwan/emotion-based-dog-filter#1]
Hi, 

How did you decide the CNN architecture to be used? Is it custom made or you referenced any research papers? 
Would be beneficial to know as I'm trying to implement the same on a different input image size.

**Comment by alvinwan** [comment]
@Prashant-mahajan It was just randomly cobbled together, haha. The task is simple enough that just a few convolutional layers and a fully-connected layer would do. For a more complex benchmark e.g., ImageNet, you might use a ResNet from He et al.
